name = "fp_utils"
version = "1.0.0"

description = "Small, composable functional helpers for Gleam."
licences = ["MIT"]
repository = { type = "github", user = "alexzzzs", repo = "Gleam-FP" }
links = [
  { title = "Documentation", href = "https://hexdocs.pm/fp_utils/" },
  { title = "Repository", href = "https://github.com/alexzzzs/Gleam-FP" }
]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
