name = "fp_utils_bench"
version = "1.0.0"

[dependencies]
fp_utils = { path = ".." }
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"